### ISSUE TITLE
The titles in the RSS reader are not clickable when outputting data in rss format

### ISSUE THREAD

**Issue by Markcco** [apify-projects/store-google-search-scraper#119]
Hello developers,
When I use Google Search Results Scraper and output data in rss format.
I found that the title is not clickable in the RSS reader.
I guess the problem is caused by the label name. The label name of the Google Search Results Scraper web link is "url".
It seems that what RSS needs is a label named "link".
How can I change "url" to "link" in settings? Or how can I create a link label and pass the value of the url?
Thank you!

**Comment by metalwarrior665** [comment]
Hello, sorry for not replying, this isn't really made for default consumption in RSS readers. If more people would need this, we could try to adjust
