### ISSUE TITLE
Is it possible to add a link field in the Google Search Results Scraper, and the value of link is the value of url? Because the url is not clickable in rss reader.

### ISSUE THREAD

**Issue by Markcco** [apify-projects/store-google-search-scraper#120]
Is it possible to add a link field in the Google Search Results Scraper, and the value of link is the value of url? Because the url is not clickable in rss reader.

**Comment by metalwarrior665** [comment]
Duplicate of https://github.com/apify-projects/store-google-search-scraper/issues/119
