### ISSUE TITLE
Page 2..10 yields duplicate results for complicated query

### ISSUE THREAD

**Issue by metalwarrior665** [apify-projects/store-google-search-scraper#39]
https://api.apify.com/v2/datasets/RCXue8sPNweq40Dly/items?format=json

**Comment by jancurn** [comment]
Please can you run it again with "Save HTML to key-value store" enabled? Will make debugging easier

**Comment by metalwarrior665** [comment]
Here you go - https://my.apify.com/view/runs/vXSi3mijnpRkXEFeQ

Looks like the pagination doesn't work at all for this type of query.

**Comment by jancurn** [comment]
I don't see any issue. Which results are duplicated? There are duplicates between pages, or on a single page?

**Comment by metalwarrior665** [comment]
Each page is exactly the same.

**Comment by metalwarrior665** [comment]
Unfortunately, we lost the queries that led to this bug.
