### ISSUE TITLE
SERP providers inconsistencies

### ISSUE THREAD

**Issue by AndreyBykov** [apify-projects/store-google-search-scraper#58]
X and V providers work perfectly, both mobile and desktop.
VA would return desktop organic results while trying to extract mobile (I think related to https://github.com/apify/actor-google-search-scraper/issues/33).
D would not accept `hl`/`gl`/`uule` params (request fails).
L would not accept `hl`/`gl`/`uule` params (request fails). Would also fail while trying to extract mobile results.

Also noticed while testing that in some rare cases `paidProducts` were on page (I think), but not in output (if I am not wrong - for 'mobile' layout).

**Comment by metalwarrior665** [comment]
This changed a lot since then so I will close for now
