### ISSUE TITLE
Organic & paid results not working (in-progress)

### ISSUE THREAD

**Issue by metalwarrior665** [apify-projects/store-google-search-scraper#71]
Example input

```
{
  "queries": "hotel paris",
  "countryCode": "fr",
  "resultsPerPage": 20,
  "maxPagesPerQuery": 10,
  "customDataFunction": "async ({ input, $, request, response, html }) => {\n  return {\n    pageTitle: $('title').text(),\n  };\n};",
  "maxConcurrency": 10,
  "saveHtml": false,
  "saveHtmlToKeyValueStore": false,
  "mobileResults": false,
  "includeUnfilteredResults": false,
  "languageCode": ""
}
```

**Comment by metalwarrior665** [comment]
Organic ones fixed, siteLinks are wrong, paidResults still missing

**Comment by metalwarrior665** [comment]
Ok, I found at least 2 new layouts. Mostly fixed all organic problems. There is still some noise in paid ads.

But in general, we will need to collect all layouts and implement unit tests for everything. I will be a work for several days.

**Comment by jancurn** [comment]
Added related issue: https://github.com/apify/actor-google-search-scraper/issues/74
